### ISSUE TITLE
拖动事件偶有bug

### ISSUE THREAD

**Issue by jerryyan1990** [lirongtong/miitvip-captcha#1]
首先，感谢作者开发了这么一款好用的组件，而且还支持VUE3

最近在使用过程中发现，在拖动滑块的过程中偶尔会出现问题。
1、鼠标不需要一直按住左键，松开左键滑块也会跟随鼠标移动而移动。
2、有时候拖动滑块会出现卡顿，鼠标在继续往前移动，但是滑块会被卡在某个地方不继续移动了。

再次感谢作者开发的组件❤

**Comment by lirongtong** [comment]
谢谢反馈，抽空我去看看

发自我的iPhone

在 2021年4月15日，09:43，JerryYan ***@***.***> 写道：

﻿

首先，感谢作者开发了这么一款好用的组件，而且还支持VUE3

最近在使用过程中发现，在拖动滑块的过程中偶尔会出现问题。
1、鼠标不需要一直按住左键，松开左键滑块也会跟随鼠标移动而移动。
2、有时候拖动滑块会出现卡顿，鼠标在继续往前移动，但是滑块会被卡在某个地方不继续移动了。

再次感谢作者开发的组件❤

**Comment by lirongtong** [comment]
已修正 .
移动事件的监听，除了最开始的 `pinterdown / touchstart` 事件，监听的依旧为对应的圆形按钮外，其它的如 `pointermove / touchmove` 等改为监听 `document.body` 元素，以便鼠标仍然按着的情况下，离开了按钮区域后无法捕捉事件，无法进行后续的处理等问题。
