### ISSUE TITLE
怎么重置验证码呢？

### ISSUE THREAD

**Issue by CrystalCoCo** [lirongtong/miitvip-captcha#12]
比如有个场景，我在登陆的时候，点击登录，进行滑块验证，验证完登录，此时密码错误导致登录报错，此时需要重置验证码，并且重新调用init的那个回调，应该怎么弄呢？

**Comment by lirongtong** [comment]
现版本暂不支持手动重置
新版本考虑外放一个方法出来重置，近期打算更新
