### ISSUE TITLE
可扩展性及组件Bug

### ISSUE THREAD

**Issue by LiuDingBang666** [lirongtong/miitvip-captcha#16]
如果验证的接口和参数都不传，@onCaptchaInit="onCaptchaInit"、@onCaptchaChecked、@onCaptchaSuccess这几个事件就都执行不了。这不是我想要的结果。并且如果接口返回的值的格式不是 res.ret 这样的数据格式的话，也会报错

**Comment by lirongtong** [comment]
> 这里的文档 https://admin.makeit.vip/components/captcha 不适用最新版本的了，这里还是旧版本的说明，新版的站点还没完善好。事件名称已经不是这些了 @onCaptchaInit、@onCaptchaChecked、@onCaptchaSuccess。

> 请先看下源码 props 参数或者 readme 示例。

> 接口定的返回格式是：
```
// 统一的返回格式，如下所示：
const result = {
    ret: {},
    data: {}
}
```
