### ISSUE TITLE
组件显示“正在加载验证码”，不能正常使用

### ISSUE THREAD

**Issue by CavalierSpirit** [lirongtong/miitvip-captcha#17]
示例logo图片不能正常显示，线下使用配置好一直“正在加载验证码”，并且logo图片不显示
![image](https://user-images.githubusercontent.com/26360495/202202461-2bff242d-23bd-41f2-b483-a2a6c2f07402.png)
<img width="453" alt="image" src="https://user-images.githubusercontent.com/26360495/202202791-905ec4ee-09d9-4228-9d5f-a72481591fa1.png">

**Comment by lirongtong** [comment]
服务器过期啦，Https 过期，已经重新发版，改为本地图片
