### ISSUE TITLE
远程验证

### ISSUE THREAD

**Issue by Toklove** [lirongtong/miitvip-captcha#22]
想知道远程验证返回的格式
这个是我返回的json数据
{"code":1,"msg":"success","time":"1691094223","data":{"cuid":"64cc0ccfc634c"}}
然后他显示下面这个效果
<img width="374" alt="截屏2023-08-04 04 23 44" src="https://github.com/lirongtong/miitvip-captcha/assets/62633268/a38c3902-1023-4a68-bbec-12b1ea060ff9">

**Comment by lirongtong** [comment]
返回格式统一按这个处理了
https://admin.makeit.vip/tools/request
