### ISSUE TITLE
远程验证的接口，需要增加headers  content-type: multipart/form-data, 代码行数如下

### ISSUE THREAD

**Issue by wangyapeng** [lirongtong/miitvip-captcha#23]
modal.tsx  //line 405

if (params.coordinate.x - 2 <= coordinateX && params.coordinate.x + 2 >= coordinateX) {
                const succcess = (data: any = {}) => {
                    setTimeout(() => {
                        closeModal('success', data)
                    }, 500)
                }
                const take = Math.round((params.time.end - params.time.start) / 10) / 100
                params.check.tip = `${take}s速度完成图片拼合验证`
                if (props.verifyAction) {
                    await $request[props.verifyMethod.toLowerCase()](
                        props.verifyAction,
                        props.verifyParams
                    )
                        .then((res: any) => {
                            if (res.ret.code === 200) {
                                params.check.correct = true
                                succcess(res.data)
                            } else error(res.ret.message)
                        })
                        .catch((err: any) => {
                            error(err.message)
                        })
                } else {
                    params.check.correct = true
                    succcess()
                }

不增加类型，koa 接收不到 body 体。

Makeit Captcha

**Comment by lirongtong** [comment]
加了 actionConfig 配置重新发版了，可自行配置请求 header

**Comment by wangyapeng** [comment]
👍🏻
