### ISSUE TITLE
logo及相关引导链接是否支持修改?

### ISSUE THREAD

**Issue by shi-lai-mu** [lirongtong/miitvip-captcha#6]
![image](https://user-images.githubusercontent.com/45140991/127757500-51694850-1a24-4d5b-a66c-fb11e97942be.png)
![image](https://user-images.githubusercontent.com/45140991/127757510-deef3dcf-7436-40d2-ac67-717ff88bdac3.png)
这三处的链接不知道是否支持定义？对于用户来说这块的文档引导似乎有些不必要吧？

**Comment by lirongtong** [comment]
暂不支持自定义，后续可更新完善
