### ISSUE TITLE
大佬,报错了

### ISSUE THREAD

**Issue by binary-zh** [lirongtong/miitvip-captcha#8]
![image](https://user-images.githubusercontent.com/23348654/152952755-0f30b776-e59d-46bb-bec9-48e787d05e1a.png)
![image](https://user-images.githubusercontent.com/23348654/152952823-bfdb4b82-076f-4d84-8444-4c6593797395.png)
好像refs是空的,不知道为什么

**Comment by lirongtong** [comment]
Node 是什么版本的？

**Comment by binary-zh** [comment]
> Node 是什么版本的？

17.0.1

**Comment by leishihong** [comment]
报错了

![image](https://user-images.githubusercontent.com/26375364/160119433-93161e03-7277-4f85-8eed-a2991d8b5a43.png)


 "makeit-captcha": "^1.2.5",

node v12.22.6
使用vue3开发的项目没有使用vite
"vue": "^3.2.26",

**Comment by lirongtong** [comment]
已修复 - 已更新发布 2.x 版本
